#FROM node:latest
FROM node:18-alpine

WORKDIR /app

###--- Copier uniquement les fichiers de dépendances
#COPY node_modules ./node_modules
#COPY . /app
COPY package*.json ./

###--- Installer les dépendances en respectant package-lock.json
#RUN npm install
#RUN apt-get update && apt-get install -y build-essential ca-certificates locales && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen
RUN npm ci --only=production

###--- Copier le reste du code
COPY . /app

###--- Exposer uniquement le port de ton app
#EXPOSE 3000 4000 5000
EXPOSE 3000

###--- Définir l’environnement en production
#ENV NODE_ENV=development
ENV NODE_ENV=production

###--- Construire l’app si besoin (React, Next.js, etc.)
RUN npm run build

###--- Utiliser l’utilisateur non-root fourni par l’image officielle
#USER root
USER node

CMD ["node", "server.js"]